### ISSUE TITLE
AMD Performance

### ISSUE THREAD

**Issue by tjesp** [tigros/Whisperer#23]
I wonder if anyone have the performance numbers for AMD gpus. I am thinking of updating from a GTX 1660 Super to a RTX 6600 card and I wonder if I can win any performance in this task?

Whisper Desktop only provides benchmarks for nVidia card and he says he is unsure of discrete AMD cards.

**Comment by tigros** [comment]
why not an Nvidia RTX 3060 in that price range? personally it will always be Nvidia because of CUDA, also Physx for subtle eye candy in games.

**Comment by NikosDi** [comment]
Whisper Desktop (and Whisperer) uses DirectCompute leveraging FP32 format, mainly.
So you have to check FP32 GFLOPs performance of cards, to get a rough idea regarding real-world performance.

My benchmark results are (for the same mp3 obviously):

Medium model
(Less is better)

nVIdia 1660             -> 21s
AMD RX 470 8GB    -> 30s
Intel Arc A380         -> 33s

Large-v1 model
(Less is better)

nVidia 1660            -> 38s
Intel Arc A380        -> 55s
(No AMD results because I removed the card from my system)

It seems that the app favors nVidia because the FP32 performance difference of 1660 is not that better than RX 470 and A380

FP32 max performance of AMD RX 6600 is around 9 GFLOPs and GTX 1660 is around 5.7 GFLOPs, so 6600 is going to be definitely faster.

Of course nVidia 3060 will be a lot faster than both with FP32 performance of ~12 GFLOPs

Although new architectures like RX 6600 and RTX 3060 measure GFLOPs differently than older ones.

But in my country RX 6600 8GB costs arounds ~195€ when RTX 3060 8GB costs around ~280€
