### ISSUE TITLE
How to add space between subtitles?

### ISSUE THREAD

**Issue by erturkdotgg** [tigros/Whisperer#36]
Hello. There is no space between two sentences when using whisper.ccp models. In other words, when the speaker finishes the sentence, the subtitle is still shown. I just want it to be displayed only when speaker is speaking. But subtitles always appear. What setting should I change?.

**Comment by tigros** [comment]
if you open the .srt in notepad do the times look ok? maybe it's your player. there's no setting for that anyway.

**Comment by TDLabs2015** [comment]
> Hello. There is no space between two sentences when using whisper.ccp models. In other words, when the speaker finishes the sentence, the subtitle is still shown. I just want it to be displayed only when speaker is speaking. But subtitles always appear. What setting should I change?.

all transcription apps are still in early stages for now some correction might be needed by end user, that's why programs like this exist so user can tweak the transcription - https://www.nikse.dk/subtitleedit, If you learn the part in the app where line breaks are, this will allow you to reconfigure delayed subtitles.
