### ISSUE TITLE
How to do TXT with Timestamp in Whisperer

### ISSUE THREAD

**Issue by Whisper-Padawan** [tigros/Whisperer#50]
Hello, i would like to transcribe with the time stamps in Whisperer.

Whisper Desktop makes this option available. See attached print.

![image](https://github.com/tigros/Whisperer/assets/143275897/3c2b5259-1ebd-438a-8835-5c43b460bce6)

Thanks.

**Comment by tigros** [comment]
i'm not coming up with a clean way to add that option in the interface, the check boxes are squished already, so how to make that option look good?

anyway here's an exe that puts timestamps, if more people ask for this we'll have to figure out a cosmetically sensible option.

someone asked to remove the timestamps a while ago, so that's why.

[whisperer.zip](https://github.com/tigros/Whisperer/files/14413791/whisperer.zip)
